"""Render dependency-free pages from reviewed locale content. Run with Python 3."""
from pathlib import Path
import json
import hashlib
from html import escape as e

ROOT = Path(__file__).resolve().parent.parent
locales = json.loads((ROOT / 'content/locales.json').read_text())
EXPECTED = {'en', 'zh-Hans', 'zh-Hant', 'ja', 'ko', 'de', 'fr', 'es', 'pt-BR'}
assert set(locales) == EXPECTED
keys = set(locales['en'])
for lang, t in locales.items():
    assert set(t) == keys, (lang, 'inconsistent keys')
    assert len(t['questions']) == 6 and len(t['policy']) == 7 and len(t['facts']) == 4
    assert all(isinstance(x, str) and x.strip() for x in t.values() if not isinstance(x, list))
    for key in ('questions', 'policy', 'facts'):
        assert all(len(pair) == 2 and all(isinstance(x, str) and x.strip() for x in pair) for pair in t[key])

# Keep the existing hand-drawn mark rather than replacing the site's visual identity.
mark = (ROOT / 'content/mark.svg').read_text().strip()

def card(title, text, kind=''):
    heading = f'<h3>{e(title)}</h3>' if title else ''
    return f'<div class="card {kind}">{heading}<p>{e(text)}</p></div>'

def contact(t):
    return (f'<p class="mail">{e(t["primary"])}: <a href="mailto:610516498@qq.com">610516498@qq.com</a></p>'
            f'<p class="mail">{e(t["backup"])}: <a href="mailto:songlaoshi666@gmail.com">songlaoshi666@gmail.com</a></p>')

def article(lang, t, privacy):
    title = 'BreathZen — ' + t['privacy' if privacy else 'support']
    tagline = t['privacyTagline' if privacy else 'tagline']
    description = t['privacyBrief'] if privacy else t['lead']
    result = [f'<article id="lang-{lang}" lang="{lang}" data-title="{e(title, quote=True)}" data-heading="{e(t["privacyHeading"] if privacy else ("波纹呼吸" if lang == "zh-Hans" else "波紋呼吸" if lang == "zh-Hant" else "BreathZen"), quote=True)}" data-tagline="{e(tagline, quote=True)}" data-description="{e(description, quote=True)}" data-language="{e(t["language"], quote=True)}" data-footer="{e(t["support"] if privacy else t["privacy"], quote=True)}">']
    if privacy:
        result += [f'<p class="lead"><strong>{e(title)}</strong><br>{e(t["effective"])}<br><small>{e(t["updated"])}</small></p>', '<div class="fact-grid">']
        for heading, text in t['facts']:
            result.append(f'<div class="fact"><span class="eyebrow">{e(heading)}</span><p>{e(text)}</p></div>')
        result.append('</div>')
        for i, (heading, text) in enumerate(t['policy']):
            result += [f'<h2>{e(heading)}</h2>', card('', text)]
            if i == 3:
                result.append(f'<p class="policy-link"><a href="https://www.apple.com/legal/privacy/">{e(t["applePolicy"])}</a></p>')
        result += [f'<h2>{e(t["contact"])}</h2>', f'<div class="card"><p>{e(t["privacyContact"])}</p>{contact(t)}</div>', f'<p class="lead"><a data-local-link href="index.html?lang={lang}">{e(t["back"])}</a></p>']
    else:
        result += [f'<p class="lead">{e(t["lead"])}</p>', f'<h2>{e(t["contact"])}</h2>', f'<div class="card">{contact(t)}<p>{e(t["technical"])}</p></div>', f'<h2>{e(t["faq"])}</h2>']
        for heading, text in t['questions']:
            result.append(card(heading, text))
        result += [f'<h2>{e(t["requirements"])}</h2>', card('', t['requirementsText']), f'<h2>{e(t["safety"])}</h2>', card('', t['safetyText'], 'notice'), f'<h2>{e(t["privacy"])}</h2>', f'<div class="card"><p>{e(t["privacyBrief"])}</p><p><a data-local-link href="privacy.html?lang={lang}">{e(t["readPolicy"])}</a></p></div>']
    result.append('</article>')
    return '\n'.join(result)

asset_version = hashlib.sha256((ROOT / 'breathzen.css').read_bytes() + (ROOT / 'breathzen.js').read_bytes()).hexdigest()[:10]

for privacy, filename in [(False, 'index.html'), (True, 'privacy.html')]:
    en = locales['en']
    title = 'BreathZen — ' + en['privacy' if privacy else 'support']
    nav = '\n'.join(f'<a href="?lang={lang}#lang-{lang}" data-lang="{lang}" lang="{lang}" hreflang="{lang}">{e(t["name"])}</a>' for lang, t in locales.items())
    articles = '\n\n'.join(article(lang, t, privacy) for lang, t in locales.items())
    footer_target = 'index.html' if privacy else 'privacy.html'
    output = f'''<!doctype html>
<!-- Generated by scripts/build.py from content/locales.json. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(title)}</title>
  <meta name="description" content="{e(en['privacyBrief'] if privacy else en['lead'], quote=True)}">
  <link rel="stylesheet" href="breathzen.css?v={asset_version}">
  <script src="breathzen.js?v={asset_version}" defer></script>
</head>
<body>
<div class="shell">
  <header>
    {mark}
    <h1>{e(en['privacyHeading'] if privacy else 'BreathZen')}</h1>
    <p class="tagline">{e(en['privacyTagline'] if privacy else en['tagline'])}</p>
    <hr class="orbit-rule">
  </header>
  <nav class="languages" aria-label="Language">{nav}</nav>
  <main>{articles}</main>
  <footer>BreathZen · <a data-local-link data-footer-link href="{footer_target}?lang=en">{e(en['support'] if privacy else en['privacy'])}</a></footer>
</div>
</body>
</html>
'''
    (ROOT / filename).write_text(output)
print('Rendered support and privacy pages in all 9 languages.')
